apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: pushgateway
  name: pushgateway
spec:
  ports:
    - name: "9091"
      port: 9091
      targetPort: 9091
    - name: 9091-tcp
      port: 9091
      targetPort: 9091
  selector:
    io.kompose.service: pushgateway
status:
  loadBalancer: {}
