apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.28.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: pushgateway
  name: pushgateway
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: pushgateway
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.28.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-default: "true"
        io.kompose.service: pushgateway
    spec:
      containers:
        - image: prom/pushgateway:latest
          name: pushgateway
          ports:
            - containerPort: 9091
          resources: {}
      restartPolicy: Always
status: {}
